import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

file = pd.read_csv('output.csv')

plt.figure()
plt.plot(file['xd'].values, file['yd'].values, label='xy trajectory', color='black', linestyle='dashed')
plt.plot(file['x'].values, file['y'].values, label='xy')
plt.title('trajectory')
plt.xlabel('x [m]')
plt.ylabel('y [m]')
plt.gca().set_aspect('equal')
plt.grid()
plt.legend()

plt.figure()
plt.subplot(2, 1, 1)
plt.plot(file['t'].values, np.degrees(file['dphi1'].values), label='$\\dot{\\phi}_1$')
plt.plot(file['t'].values, np.degrees(file['dtheta1'].values), label='$\\dot{\\theta}_1$')
plt.plot(file['t'].values, np.degrees(file['dtheta2'].values), label='$\\dot{\\theta}_2$')
plt.title('control signals')
plt.xlabel('t [s]')
plt.ylabel('$\\dot{\\eta}$ [deg/s]')
plt.xlim(0, max(file['t'].values))
plt.legend()
plt.grid()
plt.subplot(2, 1, 2)
plt.plot(file['t'].values, np.degrees(file['phi1'].values), label='$\\phi_1$')
plt.plot(file['t'].values, np.degrees(file['theta1'].values), label='$\\theta_1$')
plt.plot(file['t'].values, np.degrees(file['phi2'].values), label='$\\phi_2$')
plt.plot(file['t'].values, np.degrees(file['theta2'].values), label='$\\theta_2$')
plt.xlabel('t [s]')
plt.ylabel('gimbal angles [deg]')
plt.xlim(0, max(file['t'].values))
plt.legend()
plt.grid()

plt.figure()
plt.subplot(2, 1, 1)
plt.plot(file['t'].values, file['x'].values - file['xd'].values, label='x')
plt.plot(file['t'].values, file['y'].values - file['yd'].values, label='y')
plt.title('trajectory tracking error')
plt.xlabel('t [s]')
plt.ylabel('error [m]')
plt.grid()
plt.legend()
plt.subplot(2, 1, 2)
plt.plot(file['t'].values, file['theta'].values - file['thetad'].values, label='$\\theta$')
plt.xlabel('t [s]')
plt.ylabel('error [rad]')
plt.grid()
plt.legend()

plt.show()
