import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

file = pd.read_csv('output.csv')

plt.figure()
plt.subplot(2, 1, 1)
plt.plot(file['xd'].values, file['yd'].values, label='xy trajectory', color='black')
plt.plot(file['xs'].values, file['ys'].values, label='xy reference', color='black', linestyle='dashed')
plt.plot(file['x'].values, file['y'].values, label='xy', color='red')
plt.title('trajectory')
plt.xlabel('x [m]')
plt.ylabel('y [m]')
plt.gca().set_aspect('equal')
plt.grid()
plt.legend()
plt.subplot(2, 1, 2)
plt.plot(file['t'].values, file['thetad'].values, label='$\\theta$ trajectory', color='black')
plt.plot(file['t'].values, file['thetas'].values, label='$\\theta$ reference', color='black', linestyle='dashed')
plt.plot(file['t'].values, file['theta'].values, label='$\\theta$', color='red')
plt.xlabel('t [s]')
plt.ylabel('$\\theta$ [rad]')
plt.grid()
plt.legend()

plt.figure()
plt.subplot(2, 1, 1)
plt.plot(file['t'].values, file['eta1'].values, label='$\\eta_1$')
plt.plot(file['t'].values, file['eta2'].values, label='$\\eta_2$')
#plt.plot(file['t'].values, file['eta3'].values, label='$\\eta_3$')
plt.plot(file['t'].values, file['eta4'].values, label='$\\eta_4$')
#plt.plot(file['t'].values, file['eta5'].values, label='$\\eta_5$')
plt.title('control signals')
plt.xlabel('t [s]')
plt.xlim(0, max(file['t'].values))
plt.legend()
plt.grid()
plt.subplot(2, 1, 2)
plt.plot(file['t'].values, np.degrees(file['phi1'].values), label='$\\phi_1$')
plt.plot(file['t'].values, np.degrees(file['theta1'].values), label='$\\theta_1$')
plt.plot(file['t'].values, np.degrees(file['phi2'].values), label='$\\phi_2$')
plt.plot(file['t'].values, np.degrees(file['theta2'].values), label='$\\theta_2$')
plt.xlabel('t [s]')
plt.ylabel('gimbal angles [deg]')
plt.xlim(0, max(file['t'].values))
plt.legend()
plt.grid()

plt.figure()
plt.subplot(2, 1, 1)
plt.plot(file['t'].values, file['x'].values - file['xs'].values, label='$e_x$')
plt.plot(file['t'].values, file['y'].values - file['ys'].values, label='$e_y$')
plt.title('trajectory tracking error')
plt.xlabel('t [s]')
plt.ylabel('error [m]')
plt.grid()
plt.legend()
plt.subplot(2, 1, 2)
plt.plot(file['t'].values, file['theta'].values - file['thetas'].values, label='$e_\\theta$')
plt.xlabel('t [s]')
plt.ylabel('error [rad]')
plt.grid()
plt.legend()

plt.show()
